#!/live/bin/sh

### BEGIN INIT INFO
# Provides:          live-disable-services
# Required-Start:    checkfs checkroot-bootclean live-init
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: Disable services for LiveCD/USB
# Description:       Temporarily disable services for LiveCD/USB
### END INIT INFO

export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

VBOX_SERVICES="
virtualbox-guest-utils
virtualbox-guest-x11
"

NFS_SERVICES="
nfs-kernel-server
"

LEAN_SERVICES="
    acpi-fakekey
    acpi-support
    bootlogs
    bluetooth
    #cherokee
    cpufrequtils
    cron
    cups
    gpm
    ifplugd
    irqbalance
    loadcpufreq
    nfs-common
    rpcbind
    rsync
    rsyslog
    saned
    smartmontools
    ssh
    stop-bootlogd
    sudo
    #transmission-daemon
"

LAPTOP_SERVICES="
    acpid
    wicd
"

XTRA_LEAN_SERVICES="
    bootlogd
    cryptdisks
    cryptdisks-early
    dns-clean
    #eeepc-acpi-scripts
    hdparm
    hwclock.sh
    hwclockfirst.sh
    ifupdown-clean
    lm-sensors
    #lvm2
    mountnfs-bootclean.sh
    mountoverflowtmp
    nfs-common
    pcmciautils
    policykit
    pppd-dns
    #svgalib-bin
    ufw
    urandom
"

MEAN_SERVICES="
    networking
    network-manager
    ntp
    resolvconf
    smbd
    nfs-kernel-server
"

NO_DBUS_SERVICES="
    dbus
"

PATH=/live/bin:$PATH

prep_main() {

    case $1 in
        start)          ;;
         stop) exit 0   ;;
            *) echo "Usage: $0 {start|stop}"
               exit 1   ;;
    esac

    local must_run
    : ${CMDLINE:=$(cat /proc/cmdline)}
    for param in $CMDLINE; do
        case "$param" in
            antiX=*|aX=*) antiX_param=${param#*=}; must_run=true ;;
           disable_srv=*) antiX_param=${param#*=}; must_run=true ;;
                nosysv=*) antiX_param=${param#*=}; must_run=true ;;
       disable_service=*) antiX_param=${param#*=}; must_run=true ;;
                    lean)        LEAN=true;        must_run=true ;;
                    mean)        MEAN=true;        must_run=true ;;
                Xtralean)   XTRA_LEAN=true;        must_run=true ;;
                  nodbus)     NO_DBUS=true;        must_run=true ;;
                    db++)   DEBUGGING=true                       ;;
        esac
    done

    DISABLE_NFS=true
    local file export_files="/etc/exports"
    for file in /etc/exports.d/*.exports ; do
		[ -f "$file" ] && export_files="$export_files $file"
	done

    [ -f /etc/exports ] && grep -q '^[[:space:]]*[^#]*/' $export_files && DISABLE_NFS=

    if [ "$antiX_param" ]; then

        # If the ## expression matches then the resulting string length is zero
        [ "${antiX_param##*[lL]*}" ] ||          LEAN=true
        [ "${antiX_param##*[mM]*}" ] ||          MEAN=true
        [ "${antiX_param##*[xX]*}" ] ||     XTRA_LEAN=true
        [ "${antiX_param##*[dD]*}" ] ||       NO_DBUS=true
        [ "${antiX_param##*[vV]*}" ] ||  DISABLE_VBOX=true
        [ "${antiX_param##*[n]*}"  ] ||   DISABLE_NFS=true
        [ "${antiX_param##*[N]*}"  ] ||   ENABLE_NTPD=true
    fi

    . /live/lib/live-init-utils.sh

    start_init_logging
    load_translation
}

main() {
    # Prevent other messages stepping on ours
    # sleep 2
    echo_script "$_Customizing_services_" $0

    if test -e /etc/init.d/virtualbox-guest-utils; then
        if test -e /live/config/virtualbox; then
            echo_live "$_Enabling_X_services_" "$(pquote Virtual Box)"
            update-rc.d virtualbox-guest-utils defaults
            update-rc.d virtualbox-guest-x11   defaults
        else
            echo_live "$_Disabling_X_services_" "$(pquote Virtual Box)"
            update-rc.d virtualbox-guest-utils remove
            update-rc.d virtualbox-guest-x11   remove
        fi
    fi

    [ "$ENABLE_NTPD" ] || disable_services ntp >/dev/null

    [ -z "$must_run" -o -n "$DISABLE_NFS" ] || exit 0

    if [ "$LEAN" ]; then

        if test -e /live/config/laptop; then
            echo_live "$_Detected_laptop_mobile_device_"
        else
            LEAN_SERVICES="$LEAN_SERVICES $LAPTOP_SERVICES"
        fi

        echo_live "$_Disabling_some_services_X_" "$(paren L, lean)"
        disable_services "$LEAN_SERVICES"
    fi

    if [ "$DISABLE_VBOX" ]; then
        echo_live "$_Disabling_X_services_Y_" "Virtual Box" "$(paren v)"
        disable_services "$VBOX_SERVICES"
    fi

    if [ "$DISABLE_NFS" ]; then
        echo_live "$_Disabling_X_services_" "NFS kernel server"
        disable_services "$NFS_SERVICES"
    fi

    if [ "$MEAN" ]; then
        echo_live "$_Disabling_network_services_X_" "$(paren M, mean)"
        disable_services "$MEAN_SERVICES"
    fi

    if [ "$XTRA_LEAN" ]; then
        echo_live "$_Disabling_more_services_X_" "$(paren X, Xtralean)"
        disable_services "$XTRA_LEAN_SERVICES"
    fi

    if [ "$NO_DBUS" ]; then
        echo_live "$_Disabling_X_services_Y_" "debus" "$(paren D, nodbus)"
        disable_services "$NO_DBUS_SERVICES"
    fi
}


#----------------------------------------------------------------------------
# function disable_services "$names" [ "$rc_dirs" ]
#
# Temporarily disable services at boot-time by moving their /etc/rc?.d/
# symlinks.  See also live-restore-services which is the script
# that returns them to their proper place at the end of initialization.
#
# Move service symlinks out of various runlevels and into the matching
# /etc/antiX-live/rc?.d  directory.
#
# If no rc_dirs are given then rc?.d is used.
#----------------------------------------------------------------------------

disable_services() {

    local names="$1" rc_dirs="${2:-rc?.d}"

    local rc_dir dest name slink moved length

    for rc_dir in /etc/$rc_dirs; do

        dest=/live/config/disabled-rc.d/${rc_dir#/etc/}
        mkdir -p $dest

        for name in $names; do
            [ -z "${name###*}" ]  && continue
            for slink in /$rc_dir/S*$name; do
                [ -e "$slink" ] || continue
                mv -f $slink $dest

                #[ "$DEBUGGING" ] || continue

                [ "$moved" ] || echo -n "    "

                # Only print out each name once
                case ",$moved," in
                    *,$name,*)
                        continue;
                        ;;
                esac

                # Wrap long lines
                if [ "${#length}" -ge "60" ]; then
                    unset length
                    echo
                    echo -n "    "
                fi
                length="$length $name"
                moved="$moved,$name"
                echo -n "${PARAM_COLOR}$name$NO_COLOR "

            done
        done
    done

    [ "$moved" ] && echo

    [ "$DEBUGGING" ] || return

    local unused
    for name in $names; do
        case ",$moved," in
            *,$name,*)
                continue
                ;;
        esac
        unused="$unused $name"
    done
    [ "$unused" ] && echo_live '  Unused: %s' "$AMBER$unused"

}

prep_main "$@"
main  2>&1 | tee -a $INIT_LOG_FILE

exit 0

