#!/live/bin/sh

### BEGIN INIT INFO
# Provides:          live-disable-services
# Required-Start:    checkfs checkroot-bootclean live-init
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: Disable services for LiveCD/USB
# Description:       Temporarily disable services for LiveCD/USB
### END INIT INFO

export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

OUT_FILE=/live/config/disabled
PAM_FILE=/etc/pam.d/login

VBOX_SERVICES="
virtualbox-guest-utils
virtualbox-guest-x11
"

NFS_SERVICES="
nfs-kernel-server
"
GPM_SERVICES="
gpm
"


LEAN_SERVICES="
    acpi-fakekey
    acpi-support
    bootlogs
    bluetooth
    #cherokee
    cpufrequtils
    cron
    cups
    ifplugd
    irqbalance
    loadcpufreq
    nfs-common
    rpcbind
    rsync
    rsyslog
    saned
    smartmontools
    ssh
    stop-bootlogd
    sudo
    #transmission-daemon
"

LAPTOP_SERVICES="
    acpid
    wicd
"

ACPID_SERVICES="
    acpid
"

WICD_SERVICES="
    wicd
"

XTRA_LEAN_SERVICES="
    bootlogd
    cryptdisks
    cryptdisks-early
    dns-clean
    #eeepc-acpi-scripts
    hdparm
    hwclock.sh
    hwclockfirst.sh
    ifupdown-clean
    lm-sensors
    lvm2
    mountnfs-bootclean.sh
    mountoverflowtmp
    nfs-common
    pcmciautils
    policykit
    pppd-dns
    #svgalib-bin
    ufw
    urandom
"

MEAN_SERVICES="
    networking
    network-manager
    ntp
    resolvconf
    smbd
    nfs-kernel-server
    wicd
    avahi-daemon
"

NO_DBUS_SERVICES="
    dbus
"

PATH=/live/bin:$PATH
. /live/lib/live-init-utils.sh

start_init_logging
load_translation

main() {

    case $1 in
        start) do_start  ;;
         stop) do_stop   ;;
            *) echo "Usage: $0 {start|stop}"
               exit 1    ;;
    esac
}

do_start() {
    local must_run param val
    : ${CMDLINE:=$(cat /live/config/proc-cmdline)}
    for param in $CMDLINE; do
        val=${param#*=}
        case "$param" in
            antiX=*|aX=*) disable_param=$val   ; must_run=true ;;
           disable_srv=*) disable_param=$val   ; must_run=true ;;
                nosysv=*) disable_param=$val   ; must_run=true ;;
       disable_service=*) disable_param=$val   ; must_run=true ;;
               disable=*) disable_param=$val   ; must_run=true ;;
                    lean)        LEAN=true;      must_run=true ;;
                    mean)        MEAN=true;      must_run=true ;;
                Xtralean)   XTRA_LEAN=true;      must_run=true ;;
                  nodbus)     NO_DBUS=true;      must_run=true ;;
                    db++)   DEBUGGING=true                     ;;
        esac
    done

    if test -x /etc/init.d/nfs-kernel-server; then
        DISABLE_NFS=true
        NFS_REASON="no exports"

        local file export_files="/etc/exports"
        for file in /etc/exports.d/*.exports ; do
            [ -f "$file" ] && export_files="$export_files $file"
        done

        [ -f /etc/exports ] && grep -q '^[[:space:]]*[^#]*/' $export_files && DISABLE_NFS=
    fi

    if [ "$disable_param" ]; then

        # If the ## expression matches then the resulting string length is zero
        [ "${disable_param##*[lL]*}" ] ||          LEAN=true
        [ "${disable_param##*[mM]*}" ] ||          MEAN=true
        [ "${disable_param##*[xX]*}" ] ||     XTRA_LEAN=true
        [ "${disable_param##*[dD]*}" ] ||       NO_DBUS=true
        [ "${disable_param##*[v]*}"  ] ||  DISABLE_VBOX=true
        [ "${disable_param##*[g]*}"  ] ||   DISABLE_GPM=true
        [ "${disable_param##*[P]*}"  ] ||    ENABLE_PAM=true
        [ "${disable_param##*[a]*}"  ] || DISABLE_ACPID=true
        [ "${disable_param##*[w]*}"  ] ||  DISABLE_WICD=true
        [ "${disable_param##*[n]*}"  ] ||   DISABLE_NFS=true
        [ "${disable_param##*[n]*}"  ] ||    NFS_REASON=n
        [ "${disable_param##*[N]*}"  ] ||   ENABLE_NTPD=true
    fi

    # Prevent other messages stepping on ours
    # sleep 2
    echo_script "$_Customizing_services_" $0

    if test -e /etc/init.d/virtualbox-guest-utils; then
        if test -e /live/config/virtualbox; then
            echo_live "$_Enabling_X_services_" "$(pquote Virtual Box)"
            update-rc.d virtualbox-guest-utils defaults
            test -e /etc/init.d/virtualbox-guest-x11 && update-rc.d virtualbox-guest-x11 defaults
        else
            echo_live "$_Disabling_X_services_" "$(pquote Virtual Box)"
            update-rc.d virtualbox-guest-utils remove
            test -e /etc/init.d/virtualbox-guest-x11 && update-rc.d virtualbox-guest-x11 remove
        fi
    fi

    [ "$ENABLE_NTPD" ] || disable_services "ntpd disable by default" ntp
    [ "$ENABLE_PAM" ]  || disable_pam_login

    [ -n "$must_run" -o -n "$DISABLE_NFS" ] || exit 0

    if [ "$LEAN" ]; then

        if test -e /live/config/laptop; then
            echo_live "$_Detected_laptop_mobile_device_"
        else
            LEAN_SERVICES="$LEAN_SERVICES $LAPTOP_SERVICES"
        fi

        echo_live "$_Disabling_some_services_X_" "$(paren L, lean)"
        disable_services "lean (l)" "$LEAN_SERVICES"
    fi

    if [ "$DISABLE_ACPID" ]; then
        echo_live "$_Disabling_X_services_Y_" "$(pquote acpid)" $(paren a)
        disable_services "acpid (a)" "$ACPID_SERVICES"
    fi

    if [ "$DISABLE_WICD" ]; then
        echo_live "$_Disabling_X_services_Y_" "$(pquote wicd)" $(paren w)
        disable_services "wicd (w)" "$WICD_SERVICES"
    fi

    if [ "$MEAN" ]; then
        echo_live "$_Disabling_network_services_X_" "$(paren M, mean)"
        disable_services "mean (m)" "$MEAN_SERVICES"
    fi

    if [ "$XTRA_LEAN" ]; then
        echo_live "$_Disabling_more_services_X_" "$(paren X, Xtralean)"
        disable_services "Xtralean (x)" "$XTRA_LEAN_SERVICES"
    fi

    if [ "$NO_DBUS" ]; then
        echo_live "$_Disabling_X_services_Y_" "debus" "$(paren D, nodbus)"
        disable_services "nodbus (d)" "$NO_DBUS_SERVICES"
    fi

    if [ "$DISABLE_VBOX" ]; then
        echo_live "$_Disabling_X_services_Y_" "Virtual Box" "$(paren v)"
        disable_services "vbox (v)" "$VBOX_SERVICES"
    fi

    if [ "$DISABLE_NFS" ]; then
        echo_live "$_Disabling_NFS_server_X_" "$(paren $NFS_REASON)"
        disable_services "nfs (n)" "$NFS_SERVICES"
    fi

    if [ "$DISABLE_GPM" ]; then
        echo_live "$_Disabling_X_services_Y_" $(pquote gpm) $(paren g)
        disable_services "gpm (g)" "$GPM_SERVICES"
    fi


    [ "$OUT" ] && echo "$OUT" | tr "," "\n" > $OUT_FILE
}


#----------------------------------------------------------------------------
# function disable_services "$name" "$services" [ "$rc_dirs" ]
#
# Temporarily disable services at boot-time by moving their /etc/rc?.d/
# symlinks.  See also live-restore-services which is the script
# that returns them to their proper place at the end of initialization.
#
# Move service symlinks out of various runlevels and into the matching
# /etc/antiX-live/rc?.d  directory.
#
# If no rc_dirs are given then rc?.d is used.
#----------------------------------------------------------------------------

disable_services() {

    local name=$1 services="$2" rc_dirs="${3:-rc?.d}"

    local rc_dir dest service slink moved length

    for rc_dir in /etc/$rc_dirs; do

        dest=/live/config/disabled-rc.d/${rc_dir#/etc/}
        mkdir -p $dest

        for service in $services; do
            [ -z "${service###*}" ]  && continue
            for slink in /$rc_dir/S*$service; do
                [ -e "$slink" ] || continue
                mv -f $slink $dest

                # Only print out each service once
                case ",$moved," in
                    *,$service,*) continue ;;
                esac

                moved="$moved,$service"
            done
        done
    done

    OUT="$OUT${OUT:+,,}#----- $name -----$moved"

    [ "$DEBUGGING" ] || return

    local unused
    for service in $services; do
        case ",$moved," in
            *,$service,*) continue ;;
        esac
        unused="$unused $service"
    done
    [ "$unused" ] && echo_live '  Unused: %s' "$AMBER$unused"
}

disable_pam_login() {
    # Turn on (off) lastlog info in console login if root persistence is (not) enabled
    # Lastlog info is not useful on non-persistent system

    #egrep -q '^[[[:space:]]*session[[:space:]]+[^[:space:]]+[[:space:]]+pam_lastlog.so[[:space:]]+silent' $PAM_FILE
    #local silent_pam=$?

    if grep -q "^PERSISTENCE=.*root" /live/config/initrd.out; then
        # On persistent systems enable lastlog but disable MOTD
        sed -r -i \
            -e 's/^\s*(session\s+[^\s]+\s+pam_lastlog.so).*/\1/'         \
            -e 's/^\s*(session\s+[^\s]+\s+pam_(exec|motd).so.*)/#-- \1/' \
            $PAM_FILE
    else
        # On non-persistent systems disable both lastlog and MOTD
        sed -i -r \
            -e 's/^\s*(session\s+[^\s]+\s+pam_lastlog.so).*/\1 silent/'  \
            -e 's/^\s*(session\s+[^\s]+\s+pam_(exec|motd).so.*)/#-- \1/' \
            $PAM_FILE
    fi
}

do_stop() {

    # Restore /etc/pam.d/login to its orignal state
    # Allows caller to adjust $ROOT directory for making change under
    # /mnt/antiX (or anywhere else)
    sed -r -i \
        -e 's/^\s*(session\s+[^\s]+\s+pam_lastlog.so).*/\1/'     \
        -e '/session\s+[^\s]+\s+pam_(exec|motd).so/ s/^#-*\s*//' \
        $ROOT$PAM_FILE
}

main "$@" 2>&1 | tee -a $INIT_LOG_FILE

exit 0

